image:
  file: .gitpod.Dockerfile

tasks:
  - name: docker, restore, build
    init: |
      docker-compose up -d
      cd src/Services
      dotnet dev-certs https 
      dotnet restore
      dotnet build

ports:
  - port: 5000
    onOpen: ignore
  - port: 1433
    onOpen: ignore

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-azuretools.vscode-docker
    - streetsidesoftware.code-spell-checker
    - redhat.vscode-yaml
    - yzhang.markdown-all-in-one
