image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      cd src/Services
      dotnet dev-certs https 
      dotnet restore
      dotnet build
vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-azuretools.vscode-docker
