name: Release
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef
    - name: Build RacketReel
      working-directory: src/RacketReel/RacketReel/RacketReel.Infrastructure
      run: dotnet build
    - name: Create migration bundle RacketReel
      working-directory: src/RacketReel/RacketReel/RacketReel.Infrastructure
      run: dotnet ef migrations bundle --self-contained -r linux-x64
    - name: Build Matches
      working-directory: src/Matches/Matches.Infrastructure
      run: dotnet build
    - name: Create migration bundle Matches
      working-directory: src/Matches/Matches.Infrastructure
      run: dotnet ef migrations bundle --self-contained -r linux-x64
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
    - name: Upload migration bundle to release Racket Reel
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src/RacketReel/RacketReel/RacketReel.Infrastructure/efbundle
        asset_name: efbundle-RacketReel
        tag: ${{ steps.tag_version.outputs.new_tag }}
    - name: Upload migration bundle to release Matches
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src/Matches/Matches.Infrastructure/efbundle
        asset_name: efbundle-Matches
        tag: ${{ steps.tag_version.outputs.new_tag }}
