name: Release
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef
    - name: Create migration bundle
      working-directory: src/RacketReel/RacketReel/RacketReel.Infrastructure
      run: dotnet ef migrations bundle --self-contained -r linux-x64
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload migration bundle to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src/RacketReel/RacketReel/RacketReel.Infrastructure/efbundle
        asset_name: efbundle
        tag: ${{ github.ref }}
